local:
  service: Disk
  root: <%= Rails.root.join('storage') %>

test:
  service: Disk
  root: <%= Rails.root.join('tmp', 'storage') %>

amazon:
  service: S3
  endpoint: <%= ENV['S3_ENDPOINT'].presence %>
  access_key_id: <%= ENV['S3_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['S3_SECRET_ACCESS_KEY'] %>
  bucket: <%= ENV['S3_BUCKET'] %>
  region: <%= ENV['S3_REGION'] %>
